---

apiVersion: v1
kind: Service
metadata:
 name: adminer-service
 labels:
  author: gow
spec:
 type: LoadBalancer
 ports:
  - port: 8080
    nodePort: 30009
    name: adminer
 selector:
  app: adminer

...
