---

apiversion: apps/v1
kind: Deployment
metadata:
 name: adminer-deployment
 labels:
  author: gow
spec:
 replicas: 1
 selector:
  matchLabels:
   app: adminer
 template:
  metadata:
   name: adminer-pod
   labels:
    app: adminer

  spec:
   containers:
    - name: adminer
      image: adminer
      ports:
       - containerPort: 8080
         name: adminer
      env:
       - name: ADMINER_DEFAULT_SERVER
         value: mysql # Mysql service name to connect to

...
