---

apiVersion: v1
kind: Pod
metadata: 
 name: nginx-pod
 labels:
  type: proxy
  author: gow
spec:
 containers:
  - name: mynginx
    image: nginx
    volumeMounts:
     - name: new-volume
       mountPath: /usr/share/nginx/html
 volumes:
  - name: new-volume
    persistentVolumeClaim:
     claimName: my-pvc

...
