---

apiVersion: v1
kind: Pod
metadata:
 name: postgress-pod
 labels:
  author: gow
  type: db
spec:
 containers:
  - name: mydb
    image: postgres
    env:
     - name: POSTGRES_PASSWORD
       value: gow
     - name: POSTGRES_USER
       value: myuser
     - name: POSTGRES_DB
       value: mydb

...
