---
apiVersion: v1
kind: Pod
metadata:
 namespace: test-ns
 name: ghost-pod
 labels:
  author: gow
  type: cms
spec:
 containers:
  - name: ghost
    image: ghost
    env:
     - name: NODE_ENV
       value: development
    ports:
     - containerPort: 2368
       hostPort: 8080

...
