---

apiVersion: v1
kind: ReplicationController
metadata:
 name: httpd-rc
 labels:
  author: gow
  type: webserver
spec:
 replicas: 3
 template:
  metadata:
   name: httpd-pod
   labels:
    author: gow
    type: webserver
  spec:
   containers:
    - name: myhttpd
      image: httpd
      ports:
       - containerPort: 80
         hostPort: 9090

...


