---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: tomcat-rs
 labels:
  author: gow
  type: appserver
spec:
 replicas: 3
 selector:
  matchLabels:
   type: appserver
 template: 
  metadata:
   name: tomcat-pod
   labels:
    author: gow
    type: appserver
  spec:
   containers:
    - name: mytomcat
      image: tomee
      ports:
       - containerPort: 8080
         hostPort : 8080

...

