---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: postgres-rs
 labels:
  author: gow
  type: db
spec:
 replicas: 1
 selector: 
  matchLabels:
   type: db
 template:
  metadata:
   name: postgres-pod
   labels: 
    author: gow
    type: db
  spec:
   containers:
    - name: mydb
      image: postgres
      env:
       - name: POSTGRES_PASSWORD
         value: gow
       - name: POSTGRES_USER
         value: myuser
       - name: POSTGRES_DB
         value: mydb

...

