
---
apiVersion: v1
kind: Service
metadata: 
 name: postgres-service
 labels:
  author: gow
spec:
 type: ClusterIP
 ports:
  - targetPort: 5432
    port: 5432
 selector:
  author: gow
  type: db

...
