---

apiVersion: v1
kind: Service
metadata:
 name: mysql
 labels:
  author: gow
  app: mysql
spec:
 clusterIP: None
 ports:
  - port: 3306
 selector:
  app: mysql

---

apiVersion: apps/v1
kind: StatefulSet
metadata: 
 name: mysql-statefulset
 labels:
  app: mysql
spec:
 replicas: 2
 serviceName: mysql
 selector:
  matchLabels:
   app: mysql
 template:
  metadata:
   name: mysql-pod
   labels:
    app: mysql
  spec:
   containers:
    - name: mysql
      image: mysql
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: gow
      volumeMounts:
       - name: newvolume
         mountPath: /var/lib/mysql
 volumeClaimTemplates:
  - metadata:
     name: newvolume
    spec:
     accessModes: ["ReadWriteOnce"]
     resources:
      requests:
       storage: 2Gi

...










      
