---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  author: gow
  type: proxy
spec:
 replicas: 2
 selector:
  matchLabels:
   type: proxy
 template:
  metadata:
   name: nginx-pod
   labels:
    author: gow
    type: proxy
  spec:
   containers:
    - name: nginx
      image: nginx
      resources:
       requests:
        memory: "64Mi"
        cpu: "250m"
       limits:
        memory: "128Mi"
        cpu: "500m"

...
